# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeVPBcpp <- function() {
    .Call(`_newTDAvec_computeVPBcpp`)
}

rcpp_hello <- function() {
    .Call(`_newTDAvec_rcpp_hello`)
}

